# Generated by Django 5.1.2 on 2025-02-10 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cobro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.mesa')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='club.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='cargo',
            field=models.ForeignKey(help_text='Relacion al cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_de_compras', to='club.cargo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cargo',
            field=models.ForeignKey(help_text='Relacion al cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='club.cargo'),
        ),
    ]
