# Generated by Django 5.1.2 on 2025-02-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_mesa_capacidad_personas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='listo_a_pagar',
            field=models.BooleanField(default=False),
        ),
    ]
