# Generated by Django 5.1.2 on 2025-03-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_evento_cliente_rentador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Bandera para dar de baja un usuario'),
        ),
    ]
