# Generated by Django 5.1.2 on 2025-03-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_cargo_nota_usuario_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='defaultpass', help_text='Contraseña del usuario', max_length=128),
        ),
    ]
