# Generated by Django 5.1.2 on 2025-03-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_usuario_contrasena"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendecompra",
            name="nota",
            field=models.TextField(blank=True, null=True),
        ),
    ]
