# Generated by Django 5.1.2 on 2025-03-07 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_ordendecompra_nota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordendecompra",
            name="completado",
        ),
        migrations.RemoveField(
            model_name="ordendecompra",
            name="mesas",
        ),
        migrations.AddField(
            model_name="ordendecompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("incluido_en_cargo", "Incluido en Cargo"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ordendecompra",
            name="mesa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes_de_compras",
                to="club.mesa",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="total_cobro",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="cantidad",
            field=models.IntegerField(help_text="Cantidad de producto solicitado"),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes_de_compras",
                to="club.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="fecha_de_orden",
            field=models.DateField(help_text="Fecha de la orden de compra"),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes_de_compras",
                to="club.producto",
            ),
        ),
        migrations.AlterField(
            model_name="ordendecompra",
            name="usuario_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes_de_compras",
                to="club.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="club.cargo",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha del día de la ganancia", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total de ganancias diarias",
                max_digits=18,
                null=True,
            ),
        ),
    ]
