# Generated by Django 5.1.2 on 2025-03-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_ordendecompra_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_solicitud',
            field=models.CharField(choices=[('M', 'Mesero'), ('C', 'Caja'), ('B', 'Bartender'), ('A', 'Admin')], max_length=1),
        ),
    ]
