# Generated by Django 5.1.2 on 2025-03-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_cargo_options_alter_cargo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargo',
            table='cargos',
        ),
    ]
