# Generated by Django 5.1.2 on 2025-03-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_alter_cargo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='fecha_de_orden',
            field=models.DateField(auto_now_add=True, help_text='Fecha de la orden de compra'),
        ),
    ]
