# Generated by Django 5.1.2 on 2025-03-09 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_alter_ordendecompra_fecha_de_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='usuario_responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_de_compras', to='club.usuario'),
            preserve_default=False,
        ),
    ]
