from .bloques import BloqueViewSet
from .clientes import ClienteViewSet
from .cortes import CorteViewSet
from .eventos import EventoViewSet
from .ganancias import GananciaViewSet
from .mesas import MesaViewSet
from .ordenes_de_compras import OrdenDeCompraViewSet
from .precio_bloque import PrecioBloqueViewSet
from .productos import ProductoViewSet
from .tickets import TicketViewSet
from .usuarios import UsuarioViewSet